repo_url: https://github.com/the-full-stack/website
repo_name: The Full Stack Website
edit_uri: edit/main/docs

site_name: The Full Stack
site_url: https://fullstackdeeplearning.com
site_description: News, community, and courses for people building AI-powered products.
site_author: The Full Stack
site_image: https://staging.fullstackdeeplearning.com/images/opengraph.png
site_image_alt: Image explaining what The Full Stack covers.

copyright: The Full Stack, 2023

theme:
  custom_dir: overrides
  favicon: images/favicon.png
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
  font: false
  logo: images/favicon.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/email_modal.js
# edit_uri: ""

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.details

plugins:
  # - ezlinks  # Enables links like [[Lecture 1: Introduction]]
  - blogging: # 3rd-party plugin for blog-style pages, https://github.com/liang2kl/mkdocs-blogging-plugin/
      dirs:
        - blog/posts
      template: overrides/custom-blog.html
      features:
        tags: {}
  - macros
  - search
  - section-index # Make top-level nav sections that contain an index.md clickable

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/full_stack_dl
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/TheFullStack
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/full-stack-deep-learning/posts/
  analytics:
    provider: google
    property: G-WQ93TYN7GT

nav:
  - Home: index.md
  - "LLM Bootcamp":
      - llm-bootcamp/index.md
      - "Spring 2023":
          - llm-bootcamp/spring-2023/index.md
          - llm-bootcamp/spring-2023/launch-an-llm-app-in-one-hour/index.md
          - llm-bootcamp/spring-2023/llm-foundations/index.md
          - llm-bootcamp/spring-2023/prompt-engineering/index.md
          - llm-bootcamp/spring-2023/augmented-language-models/index.md
          - llm-bootcamp/spring-2023/askfsdl-walkthrough/index.md
          - llm-bootcamp/spring-2023/ux-for-luis/index.md
          - llm-bootcamp/spring-2023/llmops/index.md
          - llm-bootcamp/spring-2023/whats-next/index.md
  - "Deep Learning Course":
      - course/index.md
      - "FSDL 2022":
          - course/2022/index.md
          - course/2022/lecture-1-course-vision-and-when-to-use-ml/index.md
          - course/2022/lab-0-overview/index.md
          - course/2022/lecture-2-development-infrastructure-and-tooling/index.md
          - course/2022/lab-4-experiment-management/index.md
          - course/2022/lecture-3-troubleshooting-and-testing/index.md
          - course/2022/lab-5-troubleshooting-and-testing/index.md
          - course/2022/lecture-4-data-management/index.md
          - course/2022/lab-6-data-annotation/index.md
          - course/2022/lecture-5-deployment/index.md
          - course/2022/lab-7-web-deployment/index.md
          - course/2022/lecture-6-continual-learning/index.md
          - course/2022/lab-8-model-monitoring/index.md
          - course/2022/lecture-7-foundation-models/index.md
          - course/2022/lecture-8-teams-and-pm/index.md
          - course/2022/lecture-9-ethics/index.md
          - course/2022/project-showcase/index.md
          - course/2022/announcement.md
      - Older:
          - "FSDL 2021":
              - spring2021/index.md
              - spring2021/synchronous.md
              - spring2021/projects.md
              - spring2021/lecture-1.md
              - spring2021/lab-1.md
              - spring2021/notebook-1.md
              - spring2021/lecture-2a.md
              - spring2021/lecture-2b.md
              - spring2021/lab-2.md
              - spring2021/lecture-3.md
              - spring2021/lab-3.md
              - spring2021/lecture-4.md
              - spring2021/lab-4.md
              - spring2021/lecture-5.md
              - spring2021/lecture-6.md
              - spring2021/lab-5.md
              - spring2021/lecture-7.md
              - spring2021/lecture-8.md
              - spring2021/lab-6.md
              - spring2021/lecture-9.md
              - spring2021/lab-7.md
              - spring2021/lecture-10.md
              - spring2021/lab-8.md
              - spring2021/lecture-11.md
              - spring2021/lab-9.md
              - spring2021/lecture-12.md
              - spring2021/lecture-13.md
              - spring2021/panel.md
          - "FSDL 2021 (Berkeley)": https://bit.ly/berkeleyfsdl
          - "FSDL 2020 (UW)": https://bit.ly/uwfsdl
          - "FSDL 2019 (Online)": https://fall2019.fullstackdeeplearning.com
          - "FSDL 2019 (Bootcamp)": "/march2019.html"
          - "FSDL 2018 (Bootcamp)": "/august2018.html"
  - Blog:
      - "blog/index.md"
  - "Cloud GPUs": "cloud-gpus/index.md"

watch:
  - docs
  - assets
  - mkdocs.yml
  - overrides
